import {prisma} from '../../infrastructure/database/prisma.js'; import {NotFoundException,ConflictException} from '../../core/errors.js'; import {audit} from '../../infrastructure/observability/audit.js';
import type {ReportDto} from './safety.dto.js';
export class SafetyRepository{
 public async assertTarget(userId:string){const user=await prisma.user.findFirst({where:{id:userId,status:{not:'deleted'}},select:{id:true}});if(!user)throw new NotFoundException('USER_NOT_FOUND','User not found.');}
 public async block(blocker:string,blocked:string){if(blocker===blocked)throw new ConflictException('INVALID_TARGET','You cannot block yourself.');await this.assertTarget(blocked);await prisma.$transaction([prisma.block.upsert({where:{blockerUserId_blockedUserId:{blockerUserId:blocker,blockedUserId:blocked}},create:{blockerUserId:blocker,blockedUserId:blocked},update:{}}),prisma.match.updateMany({where:{status:'active',OR:[{userAId:blocker,userBId:blocked},{userAId:blocked,userBId:blocker}]},data:{status:'unmatched',unmatchedAt:new Date()}})]);await audit(blocker,'safety.block','user',blocked);}
 public async unblock(blocker:string,blocked:string){const result=await prisma.block.deleteMany({where:{blockerUserId:blocker,blockedUserId:blocked}});if(!result.count)throw new NotFoundException('BLOCK_NOT_FOUND','Block not found.');}
 public async listBlocks(userId:string){const rows=await prisma.block.findMany({where:{blockerUserId:userId},orderBy:{createdAt:'desc'},select:{blockedUserId:true,createdAt:true}});return rows.map(row=>({userId:row.blockedUserId,blockedAt:row.createdAt.toISOString()}));}
 public async report(reporter:string,reported:string,dto:ReportDto){if(reporter===reported)throw new ConflictException('INVALID_TARGET','You cannot report yourself.');await this.assertTarget(reported);const result=await prisma.report.create({data:{reporterUserId:reporter,reportedUserId:reported,reason:dto.reason,details:dto.details?.trim()||null},select:{id:true,status:true}});await audit(reporter,'safety.report','user',reported,{reason:dto.reason});return{id:result.id.toString(),status:result.status};}
 public async listReports(){const rows=await prisma.report.findMany({orderBy:{createdAt:'desc'},take:100,select:{id:true,reporterUserId:true,reportedUserId:true,reason:true,details:true,status:true,createdAt:true,reviewedAt:true}});return rows.map(row=>({...row,id:row.id.toString(),createdAt:row.createdAt.toISOString(),reviewedAt:row.reviewedAt?.toISOString()??null}));}
 public async updateReport(id:string,status:'open'|'reviewed'|'dismissed'|'actioned',adminId:string){const row=await prisma.report.update({where:{id:BigInt(id)},data:{status,reviewedAt:new Date()}});await prisma.auditLog.create({data:{userId:adminId,action:'moderation.report.update',targetType:'report',targetId:id,metadata:{status}}});return{id:row.id.toString(),status:row.status,reviewedAt:row.reviewedAt?.toISOString()??null};}
}